---
service:
  tasks: 3
  tick_interval: 1.0

logs:
  version: 1
  disable_existing_loggers: false
  formatters:
    base:
      format: "%(asctime)s %(levelname)s %(name)s [%(taskName)s] - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: base
      stream: ext://sys.stdout
    timefile:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: base
      filename: logs/aio.log
      when: D
      interval: 1
      backupCount: 7
      encoding: utf-8
  loggers:
    aio:
      level: INFO
      handlers: [timefile, console]
      propagate: false
  root:
    level: WARNING
    handlers: [console]
