# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"\r\n\x0bPingRequest\"\x1f\n\x0cPongResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0c\x45\x63hoResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2w\n\x0bPingService\x12\x33\n\x04Ping\x12\x14.service.PingRequest\x1a\x15.service.PongResponse\x12\x33\n\x04\x45\x63ho\x12\x14.service.EchoRequest\x1a\x15.service.EchoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=26
  _globals['_PINGREQUEST']._serialized_end=39
  _globals['_PONGRESPONSE']._serialized_start=41
  _globals['_PONGRESPONSE']._serialized_end=72
  _globals['_ECHOREQUEST']._serialized_start=74
  _globals['_ECHOREQUEST']._serialized_end=104
  _globals['_ECHORESPONSE']._serialized_start=106
  _globals['_ECHORESPONSE']._serialized_end=134
  _globals['_PINGSERVICE']._serialized_start=136
  _globals['_PINGSERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
